/src/main/java/io/quarkus/it/opentelemetry/Book.java=4c197ce997011887c7b221890210166c
/src/main/java/io/quarkus/it/opentelemetry/BookResource.java=cfeac851c9f57c9bf0adc949a8a9ec1c
/src/main/java/io/quarkus/it/opentelemetry/Config.java=79f173eb63291ea9576098036b17fc72
/src/main/java/io/quarkus/it/opentelemetry/ExporterResource.java=cf9edd04164d3ec23353c4f3fd62fb4b
/src/main/java/io/quarkus/it/opentelemetry/ReactiveBookResource.java=04500d2d9a07921c9c668ba7066fd39e
/src/test/java/io/quarkus/it/opentelemetry/BookResourceIT.java=39504d48f1970a1fe9754e5cc4a2acc6
/src/test/java/io/quarkus/it/opentelemetry/BookResourceOffIT.java=206a1b5e24f6ad1b938d1bc16b748359
/src/test/java/io/quarkus/it/opentelemetry/BookResourceOffTest.java=5cfff804a9c82ee3290703edecbd384f
/src/test/java/io/quarkus/it/opentelemetry/BookResourceSanitizedIT.java=7772b3a74e425b1d6d770515452b5091
/src/test/java/io/quarkus/it/opentelemetry/BookResourceSanitizedTest.java=6819fc55b6fc23a75985aa2facd2a8f9
/src/test/java/io/quarkus/it/opentelemetry/BookResourceTest.java=17c540a735aba2645da1439127119a52
