/src/main/java/io/quarkus/it/kafka/jsonschema/JsonSchemaEndpoint.java=a5e040318625a30f1381bed904147ab6
/src/main/java/io/quarkus/it/kafka/jsonschema/JsonSchemaKafkaCreator.java=a0e34f54e9aa80acf2401506d54f4f28
/src/main/java/io/quarkus/it/kafka/jsonschema/Pet.java=a6f3065c40c6c393edf4f681e3c11939
/src/test/java/io/quarkus/it/kafka/KafkaJsonSchemaIT.java=b979560c19e31cd029c2d665d00db9a7
/src/test/java/io/quarkus/it/kafka/KafkaJsonSchemaTest.java=2b3feb4d5b5de07c01671c51424b6892
/src/test/java/io/quarkus/it/kafka/KafkaJsonSchemaTestBase.java=caf51fc100b606d538f162da57720bc6
/src/test/java/io/quarkus/it/kafka/KafkaResource.java=273cab32b0b8fe92883ec1cd6513dc0a
