/src/main/java/io/quarkus/it/kubernetes/client/ConfigMapProperties.java=18e114c3cb428a0bb50477d711df4d6e
/src/main/java/io/quarkus/it/kubernetes/client/Pods.java=18c8d93dbeebda8e6499ca1f7f4cc2e8
/src/main/java/io/quarkus/it/kubernetes/client/SecretProperties.java=fbccb199fa6aedb80109c4c5e59228b3
/src/main/java/io/quarkus/it/kubernetes/client/Version.java=bb703770bcb70bb4d253a528058a5a06
/src/test/java/io/quarkus/it/kubernetes/client/AbsentConfigMapPropertiesPMT.java=d53f6b3315e0c72492b999f3c059cde9
/src/test/java/io/quarkus/it/kubernetes/client/ConfigMapPropertiesIT.java=4c30d3dc690692ea94a271e9ccbf041a
/src/test/java/io/quarkus/it/kubernetes/client/ConfigMapPropertiesTest.java=43affbcc98eb8e85f4d6282fa7beb951
/src/test/java/io/quarkus/it/kubernetes/client/CustomKubernetesTestServerTestResource.java=4cd2d171e4c3453baae3e15f4f218c48
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesClientSerializationIT.java=70d1d44c6ddbd1b775af88c66a8b1e16
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesClientSerializationTest.java=f50f61cc966e58165049cc50004d7525
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesClientTest.java=767da10cb2c454a696704ee5b0c800c8
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesClientTestIT.java=bad5b0b0abcedb325a58e5a05603827b
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesTestServerOnProfileTest.java=0d959c43597717a062f452e3dae80d67
/src/test/java/io/quarkus/it/kubernetes/client/KubernetesTestServerTest.java=9e910438de4675cbdbbf035993ad57bc
/src/test/java/io/quarkus/it/kubernetes/client/NamespacedConfigMapPropertiesTest.java=0b8c016b4017e333b3fdefa3fcf7bc05
/src/test/java/io/quarkus/it/kubernetes/client/OtherCustomKubernetesServerTestResource.java=f4c272362f87b46801fd9bff97d56341
/src/test/java/io/quarkus/it/kubernetes/client/SecretPropertiesIT.java=13ec422dfa0e936fd8914fbf15c1529c
/src/test/java/io/quarkus/it/kubernetes/client/SecretPropertiesTest.java=b7a667848489c02cf7d1d11ed00020af
