/src/main/java/io/quarkus/grpc/example/streaming/StreamingEndpoint.java=7a6a9a9119ced00ceea902d417e99f6a
/src/main/java/io/quarkus/grpc/example/streaming/StreamingService.java=3d772ddbd76c787f7f8de7712ceb57dd
/src/test/java/io/quarkus/grpc/example/streaming/StreamingEndpointIT.java=70324b0e681586c11c52eb1907360d70
/src/test/java/io/quarkus/grpc/example/streaming/StreamingEndpointTest.java=a91b86830ccfb1b9d10c203041461387
/src/test/java/io/quarkus/grpc/example/streaming/StreamingEndpointTestBase.java=46d5af064b238393330732425bf77017
