/src/test/java/io/quarkus/kubernetes/client/devservices/it/DevServicesKubernetesTest.java=935a0b0924f86a2c68a193a12065cbf0
/src/test/java/io/quarkus/kubernetes/client/devservices/it/profiles/DevServiceKubernetes.java=c7e855032bd2c05c8783e14e2bebabe1
