/src/main/java/io/quarkus/it/management/GreetingResource.java=8c1182e3c154ea4a71e885803d3dd7ca
/src/test/java/io/quarkus/it/management/ManagementInterfaceIT.java=cfe217027afdea3590aa32b83270bd76
/src/test/java/io/quarkus/it/management/ManagementInterfaceTestCase.java=e0667599a3026c767c720e8145463b4d
