/src/main/java/io/quarkus/it/agroal/ReadOnlyDataSourceResource.java=3af116c9eaa25558dcc3205e607eb2f6
/src/test/java/io/quarkus/it/agroal/ReadOnlyDataSourceIT.java=a6c8b96f935330b9b398876556dcad56
/src/test/java/io/quarkus/it/agroal/ReadOnlyDataSourceTest.java=c57f3bfc298e8f8628495c9e0b7ed519
