/src/main/java/io/quarkus/it/aesh/ssh/CdiGreetCommand.java=16fcac05716c8d6aa1765ac3d71d2160
/src/main/java/io/quarkus/it/aesh/ssh/GreetingService.java=8ea05da861d4ca0af149f2c34c5a9426
/src/main/java/io/quarkus/it/aesh/ssh/HelloCommand.java=3cec212ef2747525bde6a72a21c0137c
/src/test/java/io/quarkus/it/aesh/ssh/AeshSshIT.java=748e9376eae39223eb4d355e4b6c7e2a
/src/test/java/io/quarkus/it/aesh/ssh/AeshSshTest.java=483c88182e778e111d943fe9f744bc43
