/src/main/java/io/quarkus/it/lra/TransactionalResource.java=9fb62e6f617067c110be9fc248272212
/src/test/java/io/quarkus/it/lra/LRADevServicesStartTest.java=e3d176d60cb5d11008d1c47ae50584ae
/src/test/java/io/quarkus/it/lra/LRAITTestClassOrderer.java=5c2fb3a826ca6285e9809bb75a6667db
/src/test/java/io/quarkus/it/lra/LRAParticipantTest.java=4afba6ff6c9c10361b09d1ad4895b7e3
/src/test/java/io/quarkus/it/lra/LRAParticipantTestNativeIT.java=116cdd5497130ffdd81d518b98656758
