/src/main/java/io/quarkus/it/keycloak/ProtectedResource.java=eb13a21d5588957d43a0dce804e43a85
/src/main/java/io/quarkus/it/keycloak/PublicResource.java=2462171275f4c07b725be0db6b8106a7
/src/test/java/io/quarkus/it/keycloak/KeycloakRealmResourceManager.java=a7eb5c713d12c314482f9f24956dd23a
/src/test/java/io/quarkus/it/keycloak/SmallRyeJwtOidcWebAppInGraalITCase.java=9e4f7a98c9d5b89670b743bac6341510
/src/test/java/io/quarkus/it/keycloak/SmallRyeJwtOidcWebAppTest.java=d1950c5e78adafad645a02521ba999d7
