/src/main/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityTestEndpoint.java=236459fa736f9179776ea54bd921779c
/src/main/java/io/quarkus/it/jpa/postgresql/JPATestReflectionEndpoint.java=cec8cb4e9bc102a7e64ffb9cb1051b67
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Address.java=8a714609962e7a6776aa0168fc5161fb
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Animal.java=394218b36e377137ab8a8feec2c5a6dc
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Customer.java=2f0e76aded478b0a816b5f3259aa9eaf
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/EntityWithJson.java=c7a814f414e64a7458a813522898e1ac
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Human.java=c4df2934d3ff49570ab70ae356c29d85
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/MyUUIDEntity.java=867e2f71376117763f9eed0ea3823607
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/NotAnEntityNotReferenced.java=79cf7616d4a3a944851cbff0ea0b293c
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Person.java=e99808691114813c776a7b1769d697cd
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/SequencedAddress.java=78435572bf9c04b66aecb4b2e7de536c
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/SomeEmbeddable.java=bc5df2d2b0a2017070de28c589e45bcd
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/Status.java=c319e4d5d9191f8a68b028533af76e49
/src/main/java/io/quarkus/it/jpa/postgresql/defaultpu/WorkAddress.java=4599612a47bdce398f8d02c5a8477467
/src/main/java/io/quarkus/it/jpa/postgresql/otherpu/EntityWithJsonOtherPU.java=006fa27f53c669fb357d0a21da9acd50
/src/main/java/io/quarkus/it/jpa/postgresql/otherpu/JsonFormatMapper.java=280d6ca41726e0302e6b52025df4b019
/src/test/java/io/quarkus/it/jpa/postgresql/ConfigOverrideTest.java=082f1af23c438e67ffd1cc4dc345c3e2
/src/test/java/io/quarkus/it/jpa/postgresql/DevServicesPostgresqFixedPortTest.java=36f065fd3444a227beae79df7304a3b4
/src/test/java/io/quarkus/it/jpa/postgresql/DevServicesPostgresqlContainerNoReuseTest.java=5e8e803d5596e8575a61edae1d4cd3a9
/src/test/java/io/quarkus/it/jpa/postgresql/DevServicesPostgresqlContainerReuseTest.java=aeddf78a77c480991df689a43c3f4db3
/src/test/java/io/quarkus/it/jpa/postgresql/HibernateOrmNoWarningsTest.java=3ebd77b733f979150b6fceab5681ca13
/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityInGraalITCase.java=8dc83bec2c9ffa0787879ee7c58f6fc2
/src/test/java/io/quarkus/it/jpa/postgresql/JPAFunctionalityTest.java=a686fae3db891655805264c73b85fd3b
/src/test/java/io/quarkus/it/jpa/postgresql/JPAReflectionInGraalITCase.java=e40537446be553b1bb26368d0b0f0bc9
/src/test/java/io/quarkus/it/jpa/postgresql/OverrideJdbcUrlBuildTimeConfigSource.java=6019ceac60935ef4ce473d0fc649ea28
/src/test/java/io/quarkus/it/jpa/postgresql/PostgresTestResourceLifecycleManager.java=909f1cc38b7c86bb2d0ab6d374f68a0d
