/src/main/java/io/quarkus/it/spatial/AbstractSpatialResource.java=81e51ec6dc02f0dd7d5cf4f72a8d188e
/src/main/java/io/quarkus/it/spatial/GeolatteResource.java=6b146305479a7f5107a6b5f49a520495
/src/main/java/io/quarkus/it/spatial/JtsResource.java=29234e8a3397ea99abe091da27cb3d3a
/src/main/java/io/quarkus/it/spatial/SpatialApplication.java=b4f1e2c8b93c84ff7e531725467f234d
/src/main/java/io/quarkus/it/spatial/geolatte/GeolatteLineEntity.java=6bc50d61c6fed2f0ed21d98fe49dafd7
/src/main/java/io/quarkus/it/spatial/geolatte/GeolattePointEntity.java=390220ea370d8beb3235ad0b5fc798b3
/src/main/java/io/quarkus/it/spatial/geolatte/GeolattePolygonEntity.java=f7fbca200ba50bfe8a6b860633e55509
/src/main/java/io/quarkus/it/spatial/jts/JtsLineEntity.java=baf71a9507629edd1f7e570b8edd266a
/src/main/java/io/quarkus/it/spatial/jts/JtsPointEntity.java=3e5a1be0f21de08cd3f5b9ae351b4f65
/src/main/java/io/quarkus/it/spatial/jts/JtsPolygonEntity.java=4977ad3c90aeebb096d026740ca23469
/src/test/java/io/quarkus/it/spatial/HibernateSpatialIT.java=2ed7eb5a8954d701f3270edf1fff7aac
/src/test/java/io/quarkus/it/spatial/HibernateSpatialTest.java=09298c648716a3a6f667f239940fed38
