/src/main/java/io/quarkus/it/jpa/mariadb/Address.java=8f14b436c24494a58ee5e6c2feccd15a
/src/main/java/io/quarkus/it/jpa/mariadb/JPAFunctionalityTestEndpoint.java=1532716f36b692e3754bb1249f6c3b46
/src/main/java/io/quarkus/it/jpa/mariadb/Offline2DialectEndpoint.java=11cefe8c034355d85bc231f4e1ecf996
/src/main/java/io/quarkus/it/jpa/mariadb/OfflineDialectDescriptor.java=a9897eca4ffe82b142b8ba8682e1d43e
/src/main/java/io/quarkus/it/jpa/mariadb/OfflineDialectEndpoint.java=4039eed118dc8fa90078c6e2aae78e43
/src/main/java/io/quarkus/it/jpa/mariadb/Person.java=9337e714788557e0fc11022a75871216
/src/test/java/io/quarkus/it/jpa/mariadb/HibernateOrmNoWarningsTest.java=6041ceaae598f5eb34d34a5d57b7f90c
/src/test/java/io/quarkus/it/jpa/mariadb/JPAFunctionalityInGraalITCase.java=a0b9ce462087069010d7b99700e00712
/src/test/java/io/quarkus/it/jpa/mariadb/JPAFunctionalityTest.java=a7be1745b46b057cbd9eb6d82142b5d0
/src/test/java/io/quarkus/it/jpa/mariadb/OfflineInGraalITCase.java=e213f4414788e1ddbff30c7160370d33
/src/test/java/io/quarkus/it/jpa/mariadb/OfflineTest.java=21690a9f035ea239c839785d85ac9af4
/src/test/java/io/quarkus/it/jpa/mariadb/StorageEngineTest.java=1e6a478a50b79a3aa8773c427f17cb31
