/src/main/java/io/quarkus/it/nat/annotation/NativeImageAnnotationsResource.java=9df252df7d6ff5a45add497a90b6a396
/src/main/java/io/quarkus/it/nat/annotation/NativeImageHints.java=a7617ba5b27c87419e08ad31be02448d
/src/test/java/io/quarkus/it/nat/annotation/NativeImageAnnotationsIT.java=7258cb262aab9d41063cef6091e5f2e7
/src/test/java/io/quarkus/it/nat/annotation/NativeImageAnnotationsTest.java=6d5dd868c69a8cb69d9765045e06b6b9
