/src/main/java/io/quarkus/it/spring/test/GreetingResource.java=326fd86ae51711a39f4e2d7c302f6a3d
/src/main/java/io/quarkus/it/spring/test/GreetingService.java=965956c21cccd1b76a020706a482562d
/src/test/java/io/quarkus/it/spring/test/SpringBootTestAnnotationIT.java=f952a08d0733cda86e067698a2424ad3
/src/test/java/io/quarkus/it/spring/test/SpringBootTestAnnotationTest.java=89efe6d4f4dcc83dc2c8a9c5d719cd77
