/src/main/java/io/quarkus/it/micrometer/security/SecuredResource.java=a299f411d00d99350a38e23601a892d7
/src/main/java/io/quarkus/it/micrometer/security/SecuredResourceOverlapping.java=f5659faac8f38567beb7542f0188953a
/src/test/java/io/quarkus/it/micrometer/security/SecuredResourceTest.java=f7cdf126bb4b6ea25675fb3cf408eb1c
