/src/main/java/io/quarkus/it/hibernate/reactive/postgresql/FriesianCow.java=e669d24776a61079e684a5fd36c4e26c
/src/main/java/io/quarkus/it/hibernate/reactive/postgresql/HibernateORMTestEndpoint.java=4280be688f6b59699ff6b8d8d6434d28
/src/main/java/io/quarkus/it/hibernate/reactive/postgresql/HibernateReactiveTestEndpoint.java=d4303343b1c1e0fed8f320c5d77a1846
/src/test/java/io/quarkus/it/hibernate/reactive/postgresql/HibernateReactiveCompatibilityORMTest.java=9cf647f74a085c23addd0b06f08ba54a
