/src/main/java/io/quarkus/it/mockbean/AlphaObserver.java=08ae14a4f9ecbccb0c2aecbf62f1046b
/src/main/java/io/quarkus/it/mockbean/BravoObserver.java=460ba02b8b158e830bbbf3faf073265a
/src/main/java/io/quarkus/it/mockbean/CapitalizerService.java=324ba7cb1ea70f8e36d9445630498a69
/src/main/java/io/quarkus/it/mockbean/CapitalizerServiceSingleton.java=649a38a461aa306c90f767f4eca57255
/src/main/java/io/quarkus/it/mockbean/DummyMapping.java=081eef62268371d1f8c30b9f016dc691
/src/main/java/io/quarkus/it/mockbean/DummyResource.java=bf8f571c20ab889ca04785feb9936f6c
/src/main/java/io/quarkus/it/mockbean/DummyService.java=9b02c301b96c028be68f81026ab85a0d
/src/main/java/io/quarkus/it/mockbean/DummyService1.java=e38c3a8fd8e9f179bffa63c20e58a55a
/src/main/java/io/quarkus/it/mockbean/DummyService2.java=88b4ed3448fabd93f44f2fc208a6d714
/src/main/java/io/quarkus/it/mockbean/DummyServiceProducer.java=99cb77489b3ae4dab24faaf85b54839b
/src/main/java/io/quarkus/it/mockbean/Foo.java=f592e2943a0ebbef10df885ca8b62a09
/src/main/java/io/quarkus/it/mockbean/FooResource.java=dd83fb686b427c295e40f680b39fc6af
/src/main/java/io/quarkus/it/mockbean/FooService.java=ccc6da28c79d21c9dfac2ab584edd3f2
/src/main/java/io/quarkus/it/mockbean/GreetingResource.java=2213f278eb5cd1559f80a5672f5346ba
/src/main/java/io/quarkus/it/mockbean/GreetingResourceSingleton.java=1cf29920e9174d6bbb9b6e23f6a005e1
/src/main/java/io/quarkus/it/mockbean/HelloService.java=5ccc962c58f1d1d4e4f22777ee027f55
/src/main/java/io/quarkus/it/mockbean/MessageService.java=73942c8e8db7b81ba95a4da95b91cda9
/src/main/java/io/quarkus/it/mockbean/MessageServiceImpl.java=044ff607e80c7e1c1ddf6b7721efdf85
/src/main/java/io/quarkus/it/mockbean/MessageServiceSingleton.java=0567e62b0e648678cab9ad2210862b8c
/src/main/java/io/quarkus/it/mockbean/MessageServiceSingletonImpl.java=e41d58b62a7e1c84cdffea7a23f13e49
/src/main/java/io/quarkus/it/mockbean/OtherUnusedService.java=9441f9c49493c09d3a92a22e145de8d2
/src/main/java/io/quarkus/it/mockbean/RequestScopedFoo.java=a0a208c9345a3852616d0aafa53ac09d
/src/main/java/io/quarkus/it/mockbean/RequestScopedFooFromProducer.java=66724202b89034252e7dbeb5020150db
/src/main/java/io/quarkus/it/mockbean/RequestScopedProducer.java=19dd9e1c7ed47802ed15003164d21070
/src/main/java/io/quarkus/it/mockbean/SameBeanInstance.java=6ea7e6ec1acf9a0d96420770cf009c57
/src/main/java/io/quarkus/it/mockbean/SuffixService.java=6f88acc478ecbb7512aa83989c4b4c02
/src/main/java/io/quarkus/it/mockbean/SuffixServiceSingleton.java=98e3e041bf1a7d19da397f45f1541f7a
/src/main/java/io/quarkus/it/mockbean/SuffixServiceSingletonProducer.java=6cbd07733f64a62964e3a9b5ee2f8794
/src/main/java/io/quarkus/it/mockbean/UnusedService.java=5eeae7339b5bc235bde47eac8881c8fe
/src/main/java/io/quarkus/it/mockbean/hello/HelloServiceImpl.java=ee60364ae7b5745a7a088b34cf3b16f6
/src/main/java/io/quarkus/it/mockbean/hello/RecordA.java=c12224a6f8e230664357e83c73e7467c
/src/main/java/io/quarkus/it/mockbean/hello/RecordB.java=342e9f4487922b59644fde5e2224c2d1
/src/test/java/io/quarkus/it/mockbean/ConfigMappingTest.java=6643004e4124516282d872fdabea5683
/src/test/java/io/quarkus/it/mockbean/DummyMappingProducer.java=cb595f9fa4ad7d115c2080566b388f02
/src/test/java/io/quarkus/it/mockbean/DummyResourceTest.java=250745b8f5ec62d65ff52d0cba29342a
/src/test/java/io/quarkus/it/mockbean/FooResourceTest.java=e93cdefb403fdf98c5983a54e830bd12
/src/test/java/io/quarkus/it/mockbean/GenericFieldsTest.java=1768b235baae546d8025c861f068d3ad
/src/test/java/io/quarkus/it/mockbean/GreetingResourceTest.java=bf281e552accde12bb790ff2cf4f093e
/src/test/java/io/quarkus/it/mockbean/GreetingSingletonResourceMockTest.java=57573464dc0941e57589052cb2b2ac01
/src/test/java/io/quarkus/it/mockbean/GreetingSingletonResourceTest.java=b302b1e2637a305b534a8923c263d8d6
/src/test/java/io/quarkus/it/mockbean/MockedObserverTest.java=b0d1a4ace3e5b92a0bf718dec898a96e
/src/test/java/io/quarkus/it/mockbean/MyContainer.java=311b36c817b1e77e52dff5a1b55e62fb
/src/test/java/io/quarkus/it/mockbean/MyContainerConsumer.java=a212c952e9842171ea6c71446f00ddd3
/src/test/java/io/quarkus/it/mockbean/MyContainerProducer.java=48e3efae20a92a2d09c4edb46991b1c8
/src/test/java/io/quarkus/it/mockbean/NestedSpyTest.java=195cb0789d61316d4ade77a007d15023
/src/test/java/io/quarkus/it/mockbean/NestedTest.java=3b239c3a49a213801650c40b98399ca0
/src/test/java/io/quarkus/it/mockbean/PerClassSpyTest.java=006d6b1a83b0a7627c9c81b55298646e
/src/test/java/io/quarkus/it/mockbean/RequestScopedFooMockTest.java=429c8797099448c8d98bfa1525099eee
/src/test/java/io/quarkus/it/mockbean/RequestScopedSpyTest.java=fd1dbd888e218f8a36ddba22ee4e26af
/src/test/java/io/quarkus/it/mockbean/SameBeanInstanceTest.java=e7f5ba51bf3710f1e2d516d806d0727b
/src/test/java/io/quarkus/it/mockbean/UnusedServiceTest.java=747e359601f5dec7ac24488cc1536c01
/src/test/java/io/quarkus/it/mockbean/WithSpiesTest.java=2a4555d7b8e4ea258f42a6d13a6e2568
/src/test/java/io/quarkus/it/mockbean/WithoutMocksTest.java=bef15ccce7586353a63362687206cbd2
/src/test/java/io/quarkus/it/mockbean/hello/HelloServiceTest.java=29a7bba12c90f35e1d45cc76b77b2e79
