/src/main/java/io/quarkus/it/jpa/attributeconverter/AttributeConverterResource.java=df5c964792763a8dd83a00dad80bc0f4
/src/main/java/io/quarkus/it/jpa/attributeconverter/EntityWithAttributeConverters.java=fb6f241ea21c9736a6441541e449f082
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataNotRequiringCDI.java=214f1e577f1ee3c5fd0a2859e0f9cbdc
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataNotRequiringCDINoInjectionConverter.java=2403f4efda99b5a52e733f6350393406
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataNotRequiringCDIVetoedConverter.java=32988c7fa49c092e8b2fa97469089ec2
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataRequiringCDI.java=05d954015410cdb1ba7a21be1d141c56
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataRequiringCDIExplicitScopeConverter.java=56dc6f52582173a0b577dc2d9b0df9c7
/src/main/java/io/quarkus/it/jpa/attributeconverter/MyDataRequiringCDIImplicitScopeConverter.java=f35ac2b5972214cf99ee2b01cc6c3b4a
/src/main/java/io/quarkus/it/jpa/configurationless/CRUDResource.java=eea7cddf6a7c02eb952c210f1a3dfa6f
/src/main/java/io/quarkus/it/jpa/configurationless/Cake.java=1407a58c9c65c602c436a22afa69b0a5
/src/main/java/io/quarkus/it/jpa/configurationless/ConfigurationlessApp.java=509d877c89ca4bc6889304367ee58aab
/src/main/java/io/quarkus/it/jpa/configurationless/Gift.java=1379b84641d11a8f2341ccf8e47ec1ca
/src/main/java/io/quarkus/it/jpa/configurationless/StartupCakeManager.java=7c5773db6aa40a342fb5c7b003bb07c1
/src/main/java/io/quarkus/it/jpa/defaultcatalogandschema/DefaultCatalogAndSchemaResource.java=4593bb37412a292b7329e7254cfcbe46
/src/main/java/io/quarkus/it/jpa/defaultcatalogandschema/EntityWithDefaultCatalogAndSchema.java=9069cbbf5d68164c966105dd003af22a
/src/main/java/io/quarkus/it/jpa/defaultcatalogandschema/Schema1MetadataBuilderContributor.java=11420792ac12467f831fb6d990e22f41
/src/main/java/io/quarkus/it/jpa/elementcollection/ElementCollectionResource.java=f410106861fc7e9717aa023a89b7667f
/src/main/java/io/quarkus/it/jpa/elementcollection/OpeningTimes.java=f359c50ab6240fbe01d5ef6dbfbaa11b
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityListenerResource.java=3a9b5c0f7015f7dd61ee9406b0eff108
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityWithListenerThroughEntityListenersAnnotationWithCDIExplicitScope.java=131179f2c0aba6be8b155a732b4bdef7
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityWithListenerThroughEntityListenersAnnotationWithCDIImplicitScope.java=0821dd4ecddd3a4156350c068d7d07c9
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityWithListenerThroughEntityListenersAnnotationWithoutCDINoInjection.java=393ede32be9c67049222399af12142dd
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityWithListenerThroughEntityListenersAnnotationWithoutCDIVetoed.java=a23bef9b4fc27dee19d335aefb33ad26
/src/main/java/io/quarkus/it/jpa/entitylistener/EntityWithListenerThroughInstanceMethods.java=d16d691b7e20ff7840cfbade828bc040
/src/main/java/io/quarkus/it/jpa/entitylistener/MyListenerNotRequiringCdiNoInjection.java=1742001985b4eecf38e49f741a2afeca
/src/main/java/io/quarkus/it/jpa/entitylistener/MyListenerNotRequiringCdiVetoed.java=23aaa8a7e9f7079da6115a2f665df9bf
/src/main/java/io/quarkus/it/jpa/entitylistener/MyListenerRequiringCdiExplicitScope.java=d8a63c2886cd9aba181f780dd657fa14
/src/main/java/io/quarkus/it/jpa/entitylistener/MyListenerRequiringCdiImplicitScope.java=1190fb2c72e8805126efe4437fe54498
/src/main/java/io/quarkus/it/jpa/entitylistener/ReceivedEvent.java=72f5b4991d2f8cba9098fa8de38a86d1
/src/main/java/io/quarkus/it/jpa/generatedvalue/CustomTenantResolver.java=a32567f864814fb99355f1d83fbbd52e
/src/main/java/io/quarkus/it/jpa/generatedvalue/EntityWithCustomGenericGeneratorReferencedAsClass.java=13fa1f077ea5297316de2e49c9c8ad07
/src/main/java/io/quarkus/it/jpa/generatedvalue/EntityWithCustomGenericGeneratorReferencedAsClassName.java=248cb8672fa5c13f2c924f380358c824
/src/main/java/io/quarkus/it/jpa/generatedvalue/EntityWithCustomIdGeneratorType.java=26698efb175e47a1cf058c7262b89579
/src/main/java/io/quarkus/it/jpa/generatedvalue/EntityWithCustomValueGeneratorType.java=e0fac02c7ca8fc10df265fa58f7ca1c4
/src/main/java/io/quarkus/it/jpa/generatedvalue/EntityWithGeneratedValues.java=20147306f8c8e5e9e7848168f7f44ccd
/src/main/java/io/quarkus/it/jpa/generatedvalue/GeneratedValueResource.java=61943e0b2859af382160b79d2da7cac2
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomGenericGeneratorReferencedAsClass.java=582072a462d9454e77468c7282efc2df
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomGenericGeneratorReferencedAsClassName.java=c5c15ddfb65d0605f98645591c5790ea
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomIdGenerator.java=242681d7e4705da4fd7fe1faa741ddbe
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomIdGeneratorAnnotation.java=28980743095b07ff99b5f343ca866d65
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomValueGenerator.java=b9613c59cfe65185c312398be68e70b6
/src/main/java/io/quarkus/it/jpa/generatedvalue/MyCustomValueGeneratorAnnotation.java=6980ae3cb421b8f0864ffa6561bb9dfc
/src/main/java/io/quarkus/it/jpa/generics/AbstractGenericMappedSuperType.java=9b98edee3b3868784e64eff5b10dc8aa
/src/main/java/io/quarkus/it/jpa/generics/IntermediateAbstractMapped.java=9f8b419c33efcedc3f67bfdeb9e14230
/src/main/java/io/quarkus/it/jpa/generics/SnapshotEventEntry.java=8e74a0b7583059ac619b3da4b185a0c7
/src/main/java/io/quarkus/it/jpa/integrator/IntegratorResource.java=aff00cb6c0f039c5bd103085edd9681c
/src/main/java/io/quarkus/it/jpa/integrator/TestIntegrator.java=cf5c43ea36caba39703a46047f431d28
/src/main/java/io/quarkus/it/jpa/jdbcmetadata/EntityWithSequenceIdentityId.java=fad4e260e989fe241889aae9e7ed42c2
/src/main/java/io/quarkus/it/jpa/jdbcmetadata/JdbcMetadataRetrievalResource.java=0d6f600abc7d11ce5c830d31ad28a72f
/src/main/java/io/quarkus/it/jpa/nonquarkus/NonQuarkusApiResource.java=6c17ed4f6518ca84ae67dbd226d082fe
/src/main/java/io/quarkus/it/jpa/nonquarkus/Person.java=22eb4ef5c0b89af35561ab1a0bf98fe7
/src/main/java/io/quarkus/it/jpa/nonquarkus/SequencedAddress.java=8fdb2f544719fcc340445a6965395927
/src/main/java/io/quarkus/it/jpa/nonquarkus/Status.java=e8a4657a966ab2fcc506a72f82d427a8
/src/main/java/io/quarkus/it/jpa/orderbyfragment/Child.java=de20b78691e9961b5f24d461c298bb38
/src/main/java/io/quarkus/it/jpa/orderbyfragment/Parent.java=8cb83b6b20da63d728bf268538b75b1d
/src/main/java/io/quarkus/it/jpa/preferredhibernatetypesoverride/EntityWithOverridablePreferredTypes.java=8aa92160c50ba61b60cc1322140b9a68
/src/main/java/io/quarkus/it/jpa/preferredhibernatetypesoverride/OverriddenPreferredTypesResource.java=313aba73caa4a5f2ea2ec5e6e13db1e3
/src/main/java/io/quarkus/it/jpa/proxy/AbstractEntity.java=d7c9463287bd46e2c725375a8ee2c63a
/src/main/java/io/quarkus/it/jpa/proxy/Cat.java=a11a1929d6f7ec60b7d1521788b7c4a7
/src/main/java/io/quarkus/it/jpa/proxy/CompanyCustomer.java=2021d35c038c4db1e2214d87f3d71e21
/src/main/java/io/quarkus/it/jpa/proxy/ConcreteEntity.java=2dcc19d4a43eb9dbbf710b1dc7804917
/src/main/java/io/quarkus/it/jpa/proxy/Customer.java=e570bf4f16ef58450b082f08a1d6ff87
/src/main/java/io/quarkus/it/jpa/proxy/Dog.java=67ca4e59c15a17174253cb6737939834
/src/main/java/io/quarkus/it/jpa/proxy/DogProxy.java=6cc3be3967447735b895f739e08fba14
/src/main/java/io/quarkus/it/jpa/proxy/IndividualCustomer.java=e5983cda86c995deca5d52a397c13b49
/src/main/java/io/quarkus/it/jpa/proxy/Pet.java=7d6f34b0e3ad817f2854f0e3e7cd4fe3
/src/main/java/io/quarkus/it/jpa/proxy/PetOwner.java=1f79525ab648caf96d3a004550aa1445
/src/main/java/io/quarkus/it/jpa/proxy/PetProxy.java=36a46371537a57ea5c13b8e1a66dba19
/src/main/java/io/quarkus/it/jpa/proxy/Project.java=613c379144702c232dbf22249b3e493d
/src/main/java/io/quarkus/it/jpa/proxy/ProxyTestEndpoint.java=1f8f779457d994baeffcf6fa007a6f58
/src/main/java/io/quarkus/it/jpa/util/BeanInstantiator.java=1c7db50966455b8011233f63faa155a3
/src/main/java/io/quarkus/it/jpa/util/MyCdiContext.java=9e518cddfd33ac89ff24b6b4e229f59d
/src/test/java/io/quarkus/it/jpa/attributeconverter/AttributeConverterInGraalITCase.java=a5dbba93a3430c8db64154755ce93291
/src/test/java/io/quarkus/it/jpa/attributeconverter/AttributeConverterTest.java=8107a263e572a7d2a782f6f823bd6aa6
/src/test/java/io/quarkus/it/jpa/configurationless/JPAConfigurationlessTest.java=1c438ef5820ee7a6d93bb912df8b78c1
/src/test/java/io/quarkus/it/jpa/configurationless/JPAConfigurationlessTestInGraalITCase.java=1835da5a9b67bddc43b91a472181daaa
/src/test/java/io/quarkus/it/jpa/configurationless/JPAElementCollectionInGraalITCase.java=e27d1da3c1c67f26c6e4ab2e75701566
/src/test/java/io/quarkus/it/jpa/configurationless/JPAElementCollectionTest.java=b5f07cd3651137126491713a144bfb9b
/src/test/java/io/quarkus/it/jpa/configurationless/JPALoadScriptTest.java=5e4680446d48d0ecd4aa00367b270b95
/src/test/java/io/quarkus/it/jpa/configurationless/JPALoadScriptTestInGraalITCase.java=5f1b0cc07cd2d3a6ca31bd81d7edc3d1
/src/test/java/io/quarkus/it/jpa/configurationless/JPAOnStartupTest.java=340b109117492754ef73ac9fd93882e3
/src/test/java/io/quarkus/it/jpa/configurationless/TestResources.java=dd6c71a1745075d3b80bdbf2622d2db9
/src/test/java/io/quarkus/it/jpa/defaultcatalogandschema/DefaultSchemaInGraalITCase.java=61854238e248e840c03ed6db76602dc5
/src/test/java/io/quarkus/it/jpa/defaultcatalogandschema/DefaultSchemaTest.java=2d826bfe51f78afa892ca406005f43be
/src/test/java/io/quarkus/it/jpa/entitylistener/EntityListenerInGraalITCase.java=cdba081fb1659fe979f57220893f102f
/src/test/java/io/quarkus/it/jpa/entitylistener/EntityListenerTest.java=4622fa5b882fe9970cf8983be9955d11
/src/test/java/io/quarkus/it/jpa/generatedvalue/GeneratedValueInGraalITCase.java=7928d3d76940acb4a5822a5d0d793157
/src/test/java/io/quarkus/it/jpa/generatedvalue/GeneratedValueTest.java=80748a40c7b439533f5d89b19eeda766
/src/test/java/io/quarkus/it/jpa/integrator/JPAIntegratorTest.java=f0b71236893e8088496c434e38ec6017
/src/test/java/io/quarkus/it/jpa/jdbcmetadata/JPAJdbcMetadataRetrievalInGraalITCase.java=23477ceab3bab53b16f9383eb46f3dfa
/src/test/java/io/quarkus/it/jpa/jdbcmetadata/JPAJdbcMetadataRetrievalTest.java=d9d09498ddf6286a8873a7be6a6fec3c
/src/test/java/io/quarkus/it/jpa/nonquarkus/NonQuarkusApiInGraalITCase.java=4eb20587201931a90b351fbe4e4d390c
/src/test/java/io/quarkus/it/jpa/nonquarkus/NonQuarkusApiTest.java=c441ff1d2120be99f75bff35531c9cb1
/src/test/java/io/quarkus/it/jpa/preferredhibernatetypesoverride/OverriddenPreferredTypesInGraalITCase.java=09b98ce59c9142b1518a5296d7f24f05
/src/test/java/io/quarkus/it/jpa/preferredhibernatetypesoverride/OverriddenPreferredTypesTest.java=d3c883c72ab68a5949afbb74ef1ede1b
/src/test/java/io/quarkus/it/jpa/proxy/ProxyInGraalITCase.java=4a3f5abc55e87d718ac92e9a39995112
/src/test/java/io/quarkus/it/jpa/proxy/ProxyTest.java=3873e550b9263580956765fef787218f
