<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.quarkus.qe.tests</groupId>
    <artifactId>quarkus-main-tests</artifactId>
    <version>3.37.3</version>
    <relativePath>../../</relativePath>
  </parent>
  <artifactId>quarkus-integration-test-grpc-proto3</artifactId>
  <version>3.37.3</version>
  <name>Quarkus - Integration Tests - gRPC - Proto v3</name>
  <description>Tests extracted from project Quarkus - Integration Tests - gRPC - Proto v3</description>
  <properties>
    <quarkus.native.builder-image.pull>missing</quarkus.native.builder-image.pull>
    <protobuf-java.version>3.25.5</protobuf-java.version>
    <quarkus.build.skip>${skipTests}</quarkus.build.skip>
    <protoc.version>3.25.5</protoc.version>
    <rootDir>../../</rootDir>
    <skipSurefireTests>${skipTests}</skipSurefireTests>
    <forbiddenapis-maven-plugin.phase>none</forbiddenapis-maven-plugin.phase>
    <protobuf-kotlin.version>3.25.5</protobuf-kotlin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>linux-aarch_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>linux-ppcle_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>linux-s390_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>linux-x86_32</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>linux-x86_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>osx-aarch_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>osx-x86_64</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>windows-x86_32</classifier>
      </dependency>
      <dependency>
        <groupId>com.google.protobuf</groupId>
        <artifactId>protoc</artifactId>
        <version>${protoc.version}</version>
        <type>exe</type>
        <classifier>windows-x86_64</classifier>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc-common</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc-codegen</artifactId>
    </dependency>
    <dependency>
      <groupId>io.grpc</groupId>
      <artifactId>grpc-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc-stubs</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate-code</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>test-pulsar</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-source-plugin</artifactId>
            <version>3.4.0</version>
            <configuration>
              <skipSource>true</skipSource>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
