/src/main/java/io/quarkus/observability/example/SimpleEndpoint.java=6d2c0ae79b42064d62263e80d7f37bfc
/src/test/java/io/quarkus/observability/test/LgtmFixedPortsTest.java=cddb6b9845658c8e6c79f72a0294b47d
