/src/main/java/io/quarkus/it/vector/VectorApplication.java=fbd8ebf8ea6ffa4bc0496ab4cb15fc7a
/src/main/java/io/quarkus/it/vector/VectorEntity.java=0bf8d551169f4147c2f204cb3b68d26d
/src/main/java/io/quarkus/it/vector/VectorResource.java=cc0229b835f81a9a042861bcedba2e40
/src/test/java/io/quarkus/it/vector/HibernateVectorIT.java=a8033395e1b35f55614881b8dce0b316
/src/test/java/io/quarkus/it/vector/HibernateVectorTest.java=236f91450c542dbf5afbf4d24e2c1e80
