/src/main/java/io/quarkus/it/undertow/elytron/AnnotationSecurityServlet.java=ceed150e75cea04793bb943d1d2cd44f
/src/main/java/io/quarkus/it/undertow/elytron/GreetingServlet.java=c7ee1f58c9e4cfb4554651e98fed118a
/src/main/java/io/quarkus/it/undertow/elytron/OpenApiServlet.java=b1856040d73cea9222efe2a592a167bc
/src/main/java/io/quarkus/it/undertow/elytron/RootResource.java=0f1737b2ccbd4f7b86c091db7dcaf439
/src/test/java/io/quarkus/it/undertow/elytron/BaseAuthIT.java=84c110684991c35a7d42733d9ff825c4
/src/test/java/io/quarkus/it/undertow/elytron/BaseAuthRestTest.java=9763a11bca390358fb6ca8b985e6b82f
/src/test/java/io/quarkus/it/undertow/elytron/BaseAuthTest.java=b577c042481ad2512e679ef98ba55537
/src/test/java/io/quarkus/it/undertow/elytron/HttpsSetup.java=1e5b73a9bef2d69b94ae193d7f37ab8b
/src/test/java/io/quarkus/it/undertow/elytron/ServletSecurityAnnotationPermissionsIT.java=0a49d0dab494583164118361d6c4c9dd
/src/test/java/io/quarkus/it/undertow/elytron/ServletSecurityAnnotationPermissionsTestCase.java=c99d476087ae0774a57b0fe0f47cae99
/src/test/java/io/quarkus/it/undertow/elytron/WebXmlPermissionsTestCase.java=200bf2d03db306b2dfeb2e3a9d127ce3
