/src/main/java/io/quarkus/it/hibernate/processor/data/MyEntityResource.java=58c5dbd260613fa1d66851d1f2b80909
/src/main/java/io/quarkus/it/hibernate/processor/data/MyOtherEntityResource.java=dc1d150ba377088081ab5c42dfd339f3
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyEntity.java=6b9f38abe7deedb5982cd5463462a926
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyRepository.java=ea5f79a1d5e47ddcad1ef87c8a57ed51
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/MyOtherEntity.java=7ee4ad0b93d631a2d93787b244ca5b18
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/MyOtherRepository.java=ad9febe3a73c1e67a83c13ced8c75df2
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateOrmDataInGraalIT.java=b4442ad08ba90bb02112cecb48102c75
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateOrmDataTest.java=1808a0f1e7304a0a916124b1c78437ff
