/src/main/java/io/quarkus/it/hibernate/jpamodelgen/data/MyEntity.java=9d39366d87554b197b205bbcf4443b4b
/src/main/java/io/quarkus/it/hibernate/jpamodelgen/data/MyEntityResource.java=d59815784188b286be1c6fdb2941ed78
/src/main/java/io/quarkus/it/hibernate/jpamodelgen/data/MyRepository.java=52e8e59efbef297c4dbd77b6d9e0641e
/src/test/java/io/quarkus/it/hibernate/jpamodelgen/data/HibernateOrmDataInGraalIT.java=dc5c1eec7f502d1317c1ba935e567b47
/src/test/java/io/quarkus/it/hibernate/jpamodelgen/data/HibernateOrmDataTest.java=7b6d6c76e5c9bea9226c57dd7774b9c5
