/src/main/java/io/quarkus/it/logging/json/GreetingResource.java=f1958ecf1871b9c09da4df64c4c417e4
/src/test/java/io/quarkus/it/logging/json/GreetingResourceTest.java=ff57b251ff476f79e75c08b66b693e1b
/src/test/java/io/quarkus/it/logging/json/NativeGreetingResourceIT.java=01408fc3728006edf426120c8409eb23
