/src/main/java/io/quarkus/grpc/FakeClass.java=3c6119f6fc1460c5cab7fb438ab640b0
/src/test/java/io/quarkus/grpc/health/MicroProfileHealthDisabledTest.java=39b9bde97ad44267213f75d365bc2431
/src/test/java/io/quarkus/grpc/health/MicroProfileHealthEnabledTest.java=90ed1d2c6d82c00ed771ac588cff9d40
