/src/main/java/io/quarkus/signals/it/HelloMessage.java=37b1e720ff9d6bd427229747f2767ffd
/src/main/java/io/quarkus/signals/it/HelloMessageLogger.java=4913ed9e7f472edd43ca1e17dbde3b5b
/src/main/java/io/quarkus/signals/it/HelloName.java=f80ad214b5cfe3a35bdcae86511ceb78
/src/main/java/io/quarkus/signals/it/HelloSignals.java=fbe67b5095b7dbb82d9b6827ccc3360e
/src/main/java/io/quarkus/signals/it/SignalsResource.java=cd02733214fe4697ff085b76cdcda393
/src/test/java/io/quarkus/signals/it/SignalsResourceIT.java=ce04b8630597f1743df8d3271ca9e0b9
/src/test/java/io/quarkus/signals/it/SignalsResourceTest.java=651e09ada8c1bf18987745c6ef2cfe3f
