/src/main/java/io/quarkus/it/oidc/dev/services/ChatWebSocket.java=993cef3e6f358666455c4015e1287f4a
/src/main/java/io/quarkus/it/oidc/dev/services/ExpiredIdentityAugmentor.java=401ad7917c6287430de686ec8cc93039
/src/main/java/io/quarkus/it/oidc/dev/services/ExpiredUpdatedSecurityIdentityWebSocket.java=773b440a1bee7a07b3027817786285b9
/src/main/java/io/quarkus/it/oidc/dev/services/RolesChangingIdentityAugmentor.java=2c4b471ec568c54d721f878fcb718c99
/src/main/java/io/quarkus/it/oidc/dev/services/SecuredResource.java=61ec64ca739059c2c910e2dd70659898
/src/main/java/io/quarkus/it/oidc/dev/services/SecurityIdentityUpdateWebSocket.java=57f906161950bbbeb42407cc5855e004
/src/main/java/io/quarkus/it/oidc/dev/services/UpdatedRoleSecurityIdentityWebSocket.java=7324ea26c05b2c263d7c6118e5618f2c
/src/test/java/io/quarkus/it/oidc/dev/services/BearerAuthenticationOidcDevServicesIT.java=797ee4b562531c2e1bafaa5c85e4ef64
/src/test/java/io/quarkus/it/oidc/dev/services/BearerAuthenticationOidcDevServicesTest.java=61e5d7330433777f7c0b3c730d2a0e15
/src/test/java/io/quarkus/it/oidc/dev/services/CodeFlowOidcDevServicesTest.java=b103c1e2c9e0fe35fbd7d5212aa2a721
/src/test/java/io/quarkus/it/oidc/dev/services/WebSocketOidcTest.java=4a8325f1cea10afd26592a79c88772cf
