/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyEntity.java=6bab34a55fc84d50713d07ffeb257b3a
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyRepository.java=42c3f41f6e2be92cba874814972c8cd4
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/SecuredFindMethodRepository.java=d1bd22f13bbbfd207b6ed633a31d8366
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/SecuredHqlMethodRepository.java=1b957e3d53f5d6bcbbb791ab8842c88b
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/SecuredSqlMethodRepository.java=23aa1ac05c5db9373707950245113fcc
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/UnaccessibleFindMethodRepository.java=d7fa728758a397020666b2db8409d177
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateRepositorySecurityTest.java=00dcec5a549d458149231a80dff34011
