/src/main/java/org/acme/GreetingResource.java=02a8c8958d63dcc0577edfedc00b7940
/src/test/java/org/acme/CheckHealthExtensionLogsOptionTest.java=f24d075f62ed040337fa25d240543bd9
/src/test/java/org/acme/ConsulContainerWithFixedPortsTestResource.java=b5769fbf49d502fc186b6075072678d4
