/src/main/java/io/quarkus/tests/dependentextension/deployment/DependentContainer.java=a5848730bd216ac381a2ba574b280f75
/src/main/java/io/quarkus/tests/dependentextension/deployment/DependentDevServicesProcessor.java=17fa44884e5692207443dd31a11c4471
/src/main/java/io/quarkus/tests/dependentextension/deployment/OptionallyDependentContainer.java=935b3b59e4ee7d952ad6c260982e47e8
