/src/main/java/io/quarkus/it/cache/infinispan/ClientRequestFilter.java=ef73a96eb24edd408eb2695011b54b33
/src/main/java/io/quarkus/it/cache/infinispan/ClientRequestService.java=4dcf5516dbfba3a5f1e7df1b73e85a17
/src/main/java/io/quarkus/it/cache/infinispan/ExpensiveResource.java=220fe1621e62c543f2110f783a678aa7
/src/main/java/io/quarkus/it/cache/infinispan/RestClientResource.java=14150b19fad048a1d85d4bea1cd094f4
/src/main/java/io/quarkus/it/cache/infinispan/SunriseRestClient.java=68964dd609ed517cd006c7fe91a86c2d
/src/main/java/io/quarkus/it/cache/infinispan/SunriseRestServerResource.java=dd8b01c39eeef323361795295971bdd8
/src/test/java/io/quarkus/it/cache/infinispan/CacheIT.java=8a65e61406d278f7c0d2aaff0561944e
/src/test/java/io/quarkus/it/cache/infinispan/CacheTest.java=c87ad74c5e271da0fb016038af534d2c
/src/test/java/io/quarkus/it/cache/infinispan/InfinispanCacheClientTestCase.java=2aa10f0f868745f5b7b287e79af8e189
