/src/main/java/io/quarkus/it/liquibase/mongodb/Fruit.java=12639ff4d6ea9e3aba70c0308a4e2bbe
/src/main/java/io/quarkus/it/liquibase/mongodb/FruitResource.java=3c398206cd0e2f362d59b426b1034d9c
/src/main/java/io/quarkus/it/liquibase/mongodb/MigrationService.java=5f91278ba30a59efe79596656cf94444
/src/main/java/io/quarkus/it/liquibase/mongodb/User.java=04ce5a7044f935c1670ef8e71beb1da4
/src/main/java/io/quarkus/it/liquibase/mongodb/UserResource.java=9772b2a51a99a659f01568104848f6d6
/src/test/java/io/quarkus/it/liquibase/mongodb/FruitResourceTest.java=9aeeaea988fd77fbe52fb22098dc8596
/src/test/java/io/quarkus/it/liquibase/mongodb/MigrationServiceTest.java=dbaa9370488a2a09c2eea60d1bc3902b
/src/test/java/io/quarkus/it/liquibase/mongodb/NativeFruitResourceTestIT.java=0b782bbba0d3166592fec66d76a22c26
/src/test/java/io/quarkus/it/liquibase/mongodb/UserResourceTest.java=6af7a1aee74ee4f2d24784b8f495510b
/src/test/java/io/quarkus/it/liquibase/mongodb/UserResourceTestIT.java=ac9663a276089154d2bac7165d6af555
