<?xml version="1.0" encoding="UTF-8"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.quarkus.qe.tests</groupId>
    <artifactId>quarkus-integration-test-devservices-old-model-extension-parent</artifactId>
    <version>3.38.2</version>
  </parent>
  <artifactId>quarkus-integration-test-devservices-old-model-extension</artifactId>
  <version>3.38.2</version>
  <name>quarkus-integration-test-devservices-old-model-extension</name>
  <description>Tests extracted from project quarkus-integration-test-devservices-old-model-extension</description>
  <properties>
    <quarkus.native.builder-image.pull>missing</quarkus.native.builder-image.pull>
    <quarkus.build.skip>${skipTests}</quarkus.build.skip>
    <skipSurefireTests>${skipTests}</skipSurefireTests>
    <forbiddenapis-maven-plugin.phase>none</forbiddenapis-maven-plugin.phase>
  </properties>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-core</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-devservices</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-extension-maven-plugin</artifactId>
        <version>${core.quarkus.version}</version>
        <configuration>
          <capabilities>
            <provides>io.quarkus.old-model-extension</provides>
          </capabilities>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
