/src/main/java/io/quarkus/it/hibernate/processor/data/MyEntityResource.java=58c5dbd260613fa1d66851d1f2b80909
/src/main/java/io/quarkus/it/hibernate/processor/data/MyOtherEntityResource.java=dc1d150ba377088081ab5c42dfd339f3
/src/main/java/io/quarkus/it/hibernate/processor/data/MySqlOnlyResource.java=1000c09d9517394389cfebd4b676a388
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyEntity.java=6b9f38abe7deedb5982cd5463462a926
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/MyRepository.java=ea5f79a1d5e47ddcad1ef87c8a57ed51
/src/main/java/io/quarkus/it/hibernate/processor/data/pudefault/SecuredMyRepository.java=74796d24cc1b8512abd263c89b332b0d
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/AuthenticatedMyOtherRepository.java=b15188b2592448fadae7084c3bbeca26
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/DenyAllMyOtherRepository.java=8c502916934582789d0d5261f6939dc2
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/MyOtherEntity.java=7ee4ad0b93d631a2d93787b244ca5b18
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/MyOtherRepository.java=ad9febe3a73c1e67a83c13ced8c75df2
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/ParentClassSecurityMyOtherRepository.java=bb464832168f98a901c531da8f423570
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/ParentClassSecurityParentMyOtherRepository.java=a2b15c51eddd7058e378f6e64e69dfc8
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/ParentMethodSecurityMyOtherRepository.java=1e1a2d66f04d671a198018e9ddbf47e6
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/ParentMethodSecurityParentMyOtherRepository.java=32f72bff4590b8dde94f9ead7f15f1c0
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/PermissionsAllowedMetaAnnotationOtherRepository.java=a28d47e8154e8cda888371e2ac3c6c32
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/PermissionsAllowedOtherRepository.java=e5928f4382cb83a8055ba69d9a06c16c
/src/main/java/io/quarkus/it/hibernate/processor/data/puother/RolesAllowedOtherRepository.java=f10efe57571ca8da159a783ed46f2863
/src/main/java/io/quarkus/it/hibernate/processor/data/pusqlonly/MySqlOnlyRepository.java=29287846e4b15af60fda3b112e8fc777
/src/main/java/io/quarkus/it/hibernate/processor/data/security/CanFindByName.java=5ac76d41f3b03b3f62f5392e89d4ee51
/src/main/java/io/quarkus/it/hibernate/processor/data/security/CanWrite1.java=afdb090975be58621890ec38da257493
/src/main/java/io/quarkus/it/hibernate/processor/data/security/CanWrite2.java=5926e74d981637ad4705c44ebcf73f35
/src/main/java/io/quarkus/it/hibernate/processor/data/security/SecuredMyEntityResource.java=7aa8538246b3ef3efbf43ba38ddc20c1
/src/main/java/io/quarkus/it/hibernate/processor/data/security/SecuredMyOtherEntityResource.java=1e73d73af696c2931bda8a2487def380
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateOrmDataInGraalIT.java=b4442ad08ba90bb02112cecb48102c75
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateOrmDataSecurityTest.java=edd46fd61a2a043d9b425114546e9b2f
/src/test/java/io/quarkus/it/hibernate/processor/data/HibernateOrmDataTest.java=17fd02cfdb672e47dd550049022c08b1
