/src/main/java/io/quarkus/it/bouncycastle/BouncyCastleFipsEndpoint.java=d3697d5f84e6ae8bc396316b0aaf0ffa
/src/test/java/io/quarkus/it/bouncycastle/BouncyCastleFipsITCase.java=bba7e6295cd48249c20f6091dd7d49a6
/src/test/java/io/quarkus/it/bouncycastle/BouncyCastleFipsTestCase.java=97049cf789595e700d7bd1fc80a1ec28
