/src/main/java/org/acme/GreetingResource.java=02a8c8958d63dcc0577edfedc00b7940
/src/test/java/org/acme/ConsulContainerWithFixedPortsTestResource.java=b5769fbf49d502fc186b6075072678d4
/src/test/java/org/acme/CustomExplicitConfigRegistrationTest.java=99298a67777ee71bf08b84a0c62178c7
/src/test/java/org/acme/DisabledRegistrationTest.java=dae1854ef8fcd23f3e214a870b5735c4
/src/test/java/org/acme/ImplicitConfigRegistrationTest.java=f20f7c23ea6b215bda37f1b9a703807e
/src/test/java/org/acme/MixedStorkServicesConfigIsolationTest.java=7890c263085da51e94349ad4e4010427
/src/test/java/org/acme/MultipleRegistrarsConfigRegistrationTest.java=0e7a46766d38e00ee2550c5d85df0f96
/src/test/java/org/acme/RegistrarConfigDoesNotLeakBetweenServicesTest.java=f6a593ba05562079ef5908d9ef521907
/src/test/java/org/acme/SingleServiceWithDiscoveryAndRegistrarConfigTest.java=85aae444bc5e633c4857545a590b811f
