/src/main/java/org/acme/GreetingResource.java=02a8c8958d63dcc0577edfedc00b7940
/src/test/java/org/acme/ConsulContainerWithFixedPortsTestResource.java=b5769fbf49d502fc186b6075072678d4
/src/test/java/org/acme/CustomExplicitConfigRegistrationTest.java=0c9c5afce7fc14f50067847549d833d1
/src/test/java/org/acme/DisabledRegistrationTest.java=8803982d11271819c8466536475ca756
/src/test/java/org/acme/ImplicitConfigRegistrationTest.java=0db5bf779dd93277a1ade73d8d2bf53a
/src/test/java/org/acme/MixedStorkServicesConfigIsolationTest.java=4043fe0b4164c097b545b4ff8cbddae1
/src/test/java/org/acme/MultipleRegistrarsConfigRegistrationTest.java=4fdd3807f60ab7287393cd80b6e1f68e
/src/test/java/org/acme/RegistrarConfigDoesNotLeakBetweenServicesTest.java=0d21aef1ca05cfc11b3ffee9b17d8544
/src/test/java/org/acme/SingleServiceWithDiscoveryAndRegistrarConfigTest.java=e3713ea82fc043ed6f6aa5d7039154e7
