/src/main/java/io/quarkus/it/jaxb/Book.java=5ad7a89560c1bd443f326d29c6a5b787
/src/main/java/io/quarkus/it/jaxb/Lambda.java=03d3d26851b8f272a0e181d53ad079b3
/src/main/java/io/quarkus/it/jaxb/Resource.java=f0c4b22837d1a16064c03c2567eeb141
/src/test/java/io/quarkus/it/jaxb/AwtJaxbTest.java=37ef8fab271b3bbe70ad8d304779e861
/src/test/java/io/quarkus/it/jaxb/AwtJaxbTestIT.java=1bf3ba914f954f2adfd5e48a985aa57c
