/src/main/java/io/quarkus/it/kafka/avro/AvroEndpoint.java=e00d3558346cae4fd650f49922cc2f78
/src/main/java/io/quarkus/it/kafka/avro/AvroKafkaCreator.java=aa13b566b959acd8f301ab1ea741fc9e
/src/test/java/io/quarkus/it/kafka/KafkaAvroIT.java=e2fb228d5ffc929565f10a4b5e38aadd
/src/test/java/io/quarkus/it/kafka/KafkaAvroMixedVersionTest.java=a388f8806549b24eed3dcc999f8c2bcd
/src/test/java/io/quarkus/it/kafka/KafkaAvroSchemaReferencesTest.java=aeb0aa67eb5aac370fb21000fb2170f6
/src/test/java/io/quarkus/it/kafka/KafkaAvroTest.java=c6a70a78beb42f40a4edd4372e5f21a3
/src/test/java/io/quarkus/it/kafka/KafkaAvroTestBase.java=1ea752d1b864a76931a442c73519972c
/src/test/java/io/quarkus/it/kafka/KafkaAvroWithKafkaCompanionTest.java=6fd362c22e3684233869abda2761a066
/src/test/java/io/quarkus/it/kafka/KafkaAvroWithTestResourceTest.java=96f8614edfb4ff1efd0a063158b7d34b
/src/test/java/io/quarkus/it/kafka/KafkaResource.java=bf23ed0653c2e5eba1f8adba5c1905c6
