name: 'Extract tests'
description: 'Extracts tests for given Quarkus release tag name'
inputs:
  tag:
    description: "Quarkus release tag"
    required: true
  gh-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Extract tests for given tag and open PR
      shell: bash
      run: |
        wget -q https://raw.githubusercontent.com/quarkus-qe/quarkus-test-extractor/refs/heads/main/extract-tests.sh
        chmod +x extract-tests.sh
        ./extract-tests.sh -v -p -g "$GH_TOKEN" -b "$RELEASE_TAG"
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_REPO: ${{ github.repository }}
        RELEASE_TAG: ${{ inputs.tag }}
    - name: Push new tag
      shell: bash
      run: |
        cd /tmp/extracted-tests
        IFS='.' read -ra ARR <<< "$RELEASE_TAG"
        QUARKUS_STREAM="${ARR[0]}.${ARR[1]}"
        gh auth setup-git
        git config --local user.email "quarkus-qe@redhat.com"
        git config --local user.name "QuarkusQE"
        git fetch tags
        git tag -f $QUARKUS_STREAM
        git push origin tag $QUARKUS_STREAM -f
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_REPO: ${{ github.repository }}
        RELEASE_TAG: ${{ inputs.tag }}
