/src/main/java/io/quarkus/tests/simpleextension/deployment/SimpleContainer.java=a0a78ebb070b481022db90be954ba1d3
/src/main/java/io/quarkus/tests/simpleextension/deployment/SimpleDevServicesProcessor.java=d918ba0e56916afd29f613724097ba94
