/src/main/java/io/quarkus/it/aesh/websocket/CdiGreetCommand.java=ecfa747407b75a23e6e1af15df156a06
/src/main/java/io/quarkus/it/aesh/websocket/GreetingService.java=d80d4e15d86585fffbba9cd6af732690
/src/main/java/io/quarkus/it/aesh/websocket/HelloCommand.java=c2ff08d0bac13010c47dc125729e697d
/src/test/java/io/quarkus/it/aesh/websocket/AeshWebSocketIT.java=e3ac96ddbced4105b0aa1b51ad938bc6
/src/test/java/io/quarkus/it/aesh/websocket/AeshWebSocketTest.java=def18b2da155de9e3aeadacff743fba1
