/src/main/java/io/quarkus/it/cache/multiplebackends/CacheManagerResource.java=759207648c98d6c6c01577b86b0a6a02
/src/main/java/io/quarkus/it/cache/multiplebackends/MultipleBackendResource.java=4ac159d1a79a5abb8fc1ed9bf0ec7665
/src/test/java/io/quarkus/it/cache/multiplebackends/MultipleBackendResourceIT.java=d2d01e1236b8eaf75c4e5a53dcf2dc27
/src/test/java/io/quarkus/it/cache/multiplebackends/MultipleBackendResourceTest.java=4f8b626e476e03db5c8622dfd2402de5
