/src/main/java/io/quarkus/it/rest/data/hibernate/Fruit.java=eb97989e4a875144dd502baa3ec5e70c
/src/main/java/io/quarkus/it/rest/data/hibernate/FruitRepository.java=27ce87ef9ac0b762afdd8c7bc91daab9
/src/main/java/io/quarkus/it/rest/data/hibernate/FruitResource.java=9e2e6e9eed333bf484680926e8585fea
/src/main/java/io/quarkus/it/rest/data/hibernate/ParamEchoResource.java=17b51eb6fe20c195fcd24ccc64f16fa6
/src/test/java/io/quarkus/it/rest/data/hibernate/FruitResourceTest.java=7ccb71451fbe9f79e8bea0df1e6ca6d2
/src/test/java/io/quarkus/it/rest/data/hibernate/ParamExtractionTest.java=b8b23e6cdcfa061b3515821d0c24eed4
