/src/test/java/io/quarkus/kubernetes/client/devservices/it/DevServicesKubernetesTest.java=b463f7b5619e01dd2afafbe368f41258
/src/test/java/io/quarkus/kubernetes/client/devservices/it/profiles/DevServiceKubernetes.java=c7e855032bd2c05c8783e14e2bebabe1
