name: 'Detect new Quarkus releases'
description: 'Detects newly released Quarkus versions'
inputs:
  gh-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Detect new releases
      id: detect
      shell: bash
      run: |
        gh release list -R quarkusio/quarkus --exclude-drafts --exclude-pre-releases -L 7 --json 'tagName' | jq '.[].tagName' | while read tag; do
          # extraction of tests for 3.8.x is not supported
          echo 'Found release with tag name' $tag
          if [[ $tag != '3.8.'* ]]; then
            branchNamedAsTagReadme="$(gh repo view quarkus-qe/quarkus-extracted-tests -b $tag)"
            if [[ "$branchNamedAsTagReadme" != *$tag* ]]; then
              tagObj=''
              tagObj+="$tag"
              tagObj+=','
              echo "There is no branch of this name, hence we need to extract tests: $tagObj"
              echo -n "$tagObj" >> tags
            else
              echo "Branch $tag already exists in this project, no test extraction is needed."
            fi
          fi
        done
        tags="$(cat tags | xargs -0)"
        if [[ -n ${tags} ]]; then
          tags="[${tags::-1}]"
        fi
        echo "Collected tags output is: $tags"
        echo "tags=$tags" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        GH_REPO: ${{ github.repository }}
outputs:
  tags:
    description: "Quarkus release tags for which no Git project branch exists."
    value: ${{ steps.detect.outputs.tags }}
