/src/main/java/io/quarkus/it/kafka/avro/AvroEndpoint.java=e00d3558346cae4fd650f49922cc2f78
/src/main/java/io/quarkus/it/kafka/avro/AvroKafkaCreator.java=c54bf6c05ad439ea41825866029371bc
/src/test/java/io/quarkus/it/kafka/KafkaAvroIT.java=27f6e4718116508809b41951b77b5cbe
/src/test/java/io/quarkus/it/kafka/KafkaAvroTest.java=c6a70a78beb42f40a4edd4372e5f21a3
/src/test/java/io/quarkus/it/kafka/KafkaAvroTestBase.java=bee7b7981fcfde07426620bcbd20d585
/src/test/java/io/quarkus/it/kafka/KafkaAvroWithKafkaCompanionTest.java=22071fe0775b737b673831f0088c7d50
/src/test/java/io/quarkus/it/kafka/KafkaAvroWithTestResourceTest.java=96f8614edfb4ff1efd0a063158b7d34b
/src/test/java/io/quarkus/it/kafka/KafkaResource.java=91fe222685a193b84531dc5017b1e03e
