/src/main/java/io/quarkus/it/audit/AuditResource.java=dabb6a0d06128d843fb03f9fba7ee77f
/src/main/java/io/quarkus/it/audit/AuditedOrder.java=69510d639ab5063de7fc7f12562250f6
/src/main/java/io/quarkus/it/audit/RevisionInfo.java=026c235bf67a9506bd4a76dd852eade1
/src/main/java/io/quarkus/it/temporal/TemporalProduct.java=4f49a791e46023eebdc69d1cea70b92c
/src/main/java/io/quarkus/it/temporal/TemporalResource.java=0858a849689b012980d1ced9534b76cf
/src/test/java/io/quarkus/it/audit/HibernateOrmAuditIT.java=38f26bc46060b7cea2cd8f9d402a1630
/src/test/java/io/quarkus/it/audit/HibernateOrmAuditTest.java=49b69f9a340630b0fb94314a67c637a2
/src/test/java/io/quarkus/it/temporal/HibernateOrmTemporalIT.java=c36871ad85c850d0c6ef62aed05b0040
/src/test/java/io/quarkus/it/temporal/HibernateOrmTemporalTest.java=45d15e1eec091c32939d7cf6b559b9b9
