/src/main/java/io/quarkus/it/spring/config/server/client/ConfigResource.java=0b1b38dec459ba0b248d5d6191cb0e41
/src/test/java/io/quarkus/spring/cloud/config/client/runtime/CommonAndTestProfilesTest.java=f64cd16f42bf7d2613d062192bf17bca
/src/test/java/io/quarkus/spring/cloud/config/client/runtime/OnlyTestProfileTest.java=37cc09f24bc2d4dc69e8a53f7bf93709
/src/test/java/io/quarkus/spring/cloud/config/client/runtime/SpringCloudConfigClientIT.java=7e7a0410eee6ed10ee948f80f6ad2505
/src/test/java/io/quarkus/spring/cloud/config/client/runtime/SpringCloudConfigServerResource.java=8a412e0f5e429d3220f98e98135f9719
