/src/main/java/io/quarkus/it/kafka/sasl/SaslKafkaEndpoint.java=27c1cbb3e117afe0c9bb855d60c562b9
/src/test/java/io/quarkus/it/kafka/KafkaSASLTestResource.java=aeab4f1977de6177906332cd81a2ce2e
/src/test/java/io/quarkus/it/kafka/SaslKafkaConsumerIT.java=0adb8f377a62e6c7a98b92a550e75905
/src/test/java/io/quarkus/it/kafka/SaslKafkaConsumerTest.java=c0909a697fbc41dce7f4a1c92d5036f2
