/src/main/java/io/quarkus/it/data/hibernate/Book.java=12de143cc561ab17dbccf64b8e7a5c9e
/src/main/java/io/quarkus/it/data/hibernate/BookResource.java=139c1e1a68dc4044af42d35906211844
/src/main/java/io/quarkus/it/data/hibernate/Person.java=44e05546e3059834c10c133b01e46970
/src/main/java/io/quarkus/it/data/hibernate/PersonResource.java=8a3e5d66e8fda51af9e1ea7ff1f98ff8
/src/main/java/io/quarkus/it/data/hibernate/PersonService.java=c5a81ff7bdb2c43994393b51df58560e
/src/test/java/io/quarkus/it/data/hibernate/QuarkusDataHibernateFunctionalityIT.java=e24d432b6567a90270f058523cb3519b
/src/test/java/io/quarkus/it/data/hibernate/QuarkusDataHibernateFunctionalityTest.java=f941f14ab8a887c7347142427c4ae129
/src/test/java/io/quarkus/it/data/hibernate/QuarkusDataHibernateInjectMockTest.java=7e2c4c475eb789fc7dd1062298d67c9f
