/src/main/java/io/quarkus/it/panache/next/Book.java=9c08b5403fd0d1d533ae103f9e85127c
/src/main/java/io/quarkus/it/panache/next/BookResource.java=3e93a30657b04af8c696f3b09e973cc4
/src/main/java/io/quarkus/it/panache/next/Person.java=ab27d4af058fad90a2999fd9cdd58522
/src/main/java/io/quarkus/it/panache/next/PersonResource.java=be61d2417c55ba8d5af037abc41e142f
/src/main/java/io/quarkus/it/panache/next/PersonService.java=0963f20c0aeedf80be8cf4c9039bdf32
/src/test/java/io/quarkus/it/panache/next/PanacheNextFunctionalityIT.java=a73f4bbbeeb05dce9ec1786150ac4c2c
/src/test/java/io/quarkus/it/panache/next/PanacheNextFunctionalityTest.java=c5288c4b26ffd55c21f62654ccdc9ec6
/src/test/java/io/quarkus/it/panache/next/PanacheNextInjectMockTest.java=9904316a98ab979686722a4385aa0af7
