/src/main/java/io/quarkus/it/hibernate/orm/cache/Citizen.java=f43178351c7a8e631853c1d50ace582d
/src/main/java/io/quarkus/it/hibernate/orm/cache/Country.java=1da88eeeceb4361ebd25f22565a621e8
/src/main/java/io/quarkus/it/hibernate/orm/cache/DataBlob.java=ec97c952aba0b94d3e9338d68be0c269
/src/main/java/io/quarkus/it/hibernate/orm/cache/DataBlobWeigher.java=ae83d50d760d7b727695b315a490c67e
/src/main/java/io/quarkus/it/hibernate/orm/cache/HibernateOrmCacheTestEndpoint.java=7bffca6e2cc84b5ef702d0a4797cb22c
/src/main/java/io/quarkus/it/hibernate/orm/cache/Item.java=bc047018157952661bdc78a95e1c65a9
/src/main/java/io/quarkus/it/hibernate/orm/cache/Person.java=71cefcb4cbfc3fed92921d1748ba36c5
/src/main/java/io/quarkus/it/hibernate/orm/cache/Pokemon.java=cd3661b5bf5d7388c7f8457ca4a4838a
/src/main/java/io/quarkus/it/hibernate/orm/cache/Trainer.java=8cdbbb8a8ca2d6f454cd8c16e3840a26
/src/test/java/io/quarkus/it/hibernate/orm/cache/HibernateOrmCacheFunctionalityInGraalITCase.java=de049904af0e6704fc3cfbcf5eb13179
/src/test/java/io/quarkus/it/hibernate/orm/cache/HibernateOrmCacheFunctionalityTest.java=e67209ccb406505bfcf228156c7efcbe
