/src/main/java/io/quarkus/it/spring/tx/ClassLevelTransactionalService.java=f348cb600efa5c21e5295442d04f84df
/src/main/java/io/quarkus/it/spring/tx/TransactionalResource.java=bd792f4587bfad019da380cb67f39857
/src/main/java/io/quarkus/it/spring/tx/TransactionalService.java=577c96fc23cc3282bc257767e47ae581
/src/test/java/io/quarkus/it/spring/tx/SpringTransactionalResourceIT.java=5ab39b14082387aec47e9884dbdc09e2
/src/test/java/io/quarkus/it/spring/tx/SpringTransactionalResourceTest.java=f1387e2b4e52c4bbbab5a76086a2b271
