/src/test/java/io/quarkus/maven/AddExtensionMojoTest.java=aa881cb145985ea41dc8e026e598e8ee
/src/test/java/io/quarkus/maven/AddExtensionsMojoTest.java=95a701de9ab31f98b86eed329791abd1
/src/test/java/io/quarkus/maven/it/AddExtensionIT.java=7b2c25ba1be9b042bfe81aa16c45981f
/src/test/java/io/quarkus/maven/it/AddedRestEndpoint.java=7f1f97353d58efc3972131b404dddd74
/src/test/java/io/quarkus/maven/it/ApplicationNameAndVersionTestUtil.java=b55f65c4ebabc1d77e7f65d05e78e6bb
/src/test/java/io/quarkus/maven/it/AuxiliaryTestsForDevMojoIT.java=1ea00771ea08d21ba2c01af1653d8886
/src/test/java/io/quarkus/maven/it/BuildIT.java=4090b6d89b3d344f48a11a2ad8a21978
/src/test/java/io/quarkus/maven/it/CodeGenIT.java=39966a1540df9ceb4eabcf65f2e76358
/src/test/java/io/quarkus/maven/it/CreateExtensionMojoIT.java=dd3b2b415e0f1b3b5e4ee8ee5667752b
/src/test/java/io/quarkus/maven/it/CreateJBangProjectMojoIT.java=0f9f4ee0f0f47cd12bc24bb0c52054da
/src/test/java/io/quarkus/maven/it/CreateProjectCodestartMojoIT.java=cc5410b5ed3c83a07385c31707d9589f
/src/test/java/io/quarkus/maven/it/CreateProjectMojoIT.java=c27cc3263d4a35d44ee0d89e0f89f8ed
/src/test/java/io/quarkus/maven/it/DevMojoIT.java=43e92d72cdaa90501d1cc15abe6c507e
/src/test/java/io/quarkus/maven/it/DisableForNative.java=9c1eaf8b7fff9004a3b8d9b5f3fe6b0a
/src/test/java/io/quarkus/maven/it/EnableForNative.java=d64cdd6ac10a1b3087c578f90c763f01
/src/test/java/io/quarkus/maven/it/FastJarQuarkusIntegrationTestIT.java=e3e91b897ed6f8d01818f971e62a3553
/src/test/java/io/quarkus/maven/it/IgnoreEntriesIT.java=6e5d334d103e8e70acd91761773a65b4
/src/test/java/io/quarkus/maven/it/ImageBuildIT.java=5cae8d0e3837a7a3e60ce5bd9856cad8
/src/test/java/io/quarkus/maven/it/JarRunnerIT.java=1cbea86bf4655de60c91e98420105373
/src/test/java/io/quarkus/maven/it/LaunchMojoTestBase.java=a5de1d2748683e538277a765481dc34c
/src/test/java/io/quarkus/maven/it/LegacyJarQuarkusIntegrationTestIT.java=c078b16522cefe98283452a7af3f87de
/src/test/java/io/quarkus/maven/it/ListExtensionsIT.java=864e8424c5b952d1ca788d236f6cc08c
/src/test/java/io/quarkus/maven/it/NativeAgentIT.java=57817075a70c308a682f499d25088d86
/src/test/java/io/quarkus/maven/it/NativeImageBundleIT.java=20c5004c323eb666ec72ece090ad59ec
/src/test/java/io/quarkus/maven/it/NativeImageIT.java=c2545ff9b0727ea40658b06989f58194
/src/test/java/io/quarkus/maven/it/PackageIT.java=6b52a247bb6ab1d3b7349f0e1f2f9342
/src/test/java/io/quarkus/maven/it/QuarkusITBase.java=97a12990e8ab26fcf1a3a1333ca1665a
/src/test/java/io/quarkus/maven/it/QuarkusTestIT.java=af0c5a8d31d14151ae4ac35366e87e48
/src/test/java/io/quarkus/maven/it/QuestionMarkInPathIntegrationTestIT.java=d4faa74f11058c574da8575c3fbc7e4a
/src/test/java/io/quarkus/maven/it/RemoteDevMojoIT.java=cc0f6f64a665d86ecf1042f5ecad676d
/src/test/java/io/quarkus/maven/it/SurefireRerunFailedTestsIT.java=33011ef2c41671cda7f1cf108fc1f301
/src/test/java/io/quarkus/maven/it/TestMojoIT.java=9e5b1cab2fbb46cef66168d9983e108d
/src/test/java/io/quarkus/maven/it/TestUtils.java=9fee5145df83afd3c50b83ef82e4d76e
/src/test/java/io/quarkus/maven/it/UberJarQuarkusIntegrationTestIT.java=02cca116d329cf37c0db14826d6c36fa
/src/test/java/io/quarkus/maven/it/VerifyIT.java=9d5436d4e767d99970aa32053e96fb33
