name: "PR"
on:
  - pull_request
jobs:
  validation:
    name: Builds project without running tests
    if: ${{ ! contains(github.ref, 'main') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Detect OS Architecture
        id: detect-os-arch
        run: |
          echo "detected-os-arch=$(uname -m)" >> "$GITHUB_OUTPUT"
      - name: Build extensions managed dependencies
        env:
          DETECTED_OS_ARCH: ${{ steps.detect-os-arch.outputs.detected-os-arch }}
        run: |
          mvn -V -B --no-transfer-progress clean install -DskipTests -DskipITs -Dextension-tests-managed-modules -Dos.detected.arch=$DETECTED_OS_ARCH
      - name: Build integration tests managed dependencies
        env:
          DETECTED_OS_ARCH: ${{ steps.detect-os-arch.outputs.detected-os-arch }}
        run: |
          mvn -V -B --no-transfer-progress clean install -DskipTests -DskipITs -Dquarkus.build.skip=false -Dintegration-tests-managed-modules -Dos.detected.arch=$DETECTED_OS_ARCH
      - name: Build with Maven
        env:
          DETECTED_OS_ARCH: ${{ steps.detect-os-arch.outputs.detected-os-arch }}
        run: |
          mvn -V -B --no-transfer-progress clean install -DskipTests -DskipITs -Dquarkus.build.skip=false -Dextensions -Dintegration-tests -Dos.detected.arch=$DETECTED_OS_ARCH
  run-tests:
    name: Linux - JVM build - Latest Version
    runs-on: ubuntu-latest
    needs: validation
    strategy:
      matrix:
        extension-set: [ "extensions-1", "extensions-2", "extensions-3", "extensions-4", "extensions-5", "extensions-6", "extensions-7", "extensions-8", "extensions-9", "extensions-10" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true
          cache: 'maven'
      - name: Extensions set '${{ matrix.extension-set }}'
        run: |
          MVN_ARGS=" -Dos.detected.arch=$(uname -m)"
          chmod +x run_tests.sh
          ./run_tests.sh 10 "${{ matrix.extension-set }}" "$MVN_ARGS" "$MVN_ARGS"