/src/main/java/io/quarkus/test/devservices/redis/TestResource.java=09ddd124ab4dd560870fcaf1b813c760
/src/test/java/io/quarkus/redis/devservices/continuoustesting/it/DevServicesRedisContinuousTestingTest.java=2402efaeb9783cb941fafc8233a30f08
/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisCustomPortITest.java=37f9d2ce83af8e058012b9408ece3246
/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisCustomPortReusableServiceITest.java=031e9481992fc2bc50e2e044049b0055
/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisITest.java=a6a6da3b26d6584fd44fffddf9b67412
/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisNonUniquePortITest.java=63873d312648457efed6b80448c3b68f
/src/test/java/io/quarkus/redis/devservices/it/DevServicesRedisRandomPortITest.java=0d2ad9f1506f681025c90e9713741ccd
/src/test/java/io/quarkus/redis/devservices/it/PlainQuarkusTest.java=4fe160dc95e18d305a1928279cd5695f
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServiceRedis.java=117447bc79f3f13e2ed68e5c473a558d
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServicesCustomPortProfile.java=7d0d05e730414ef1fdd8440a4a489a1e
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServicesCustomPortReusableServiceProfile.java=8a1c9805cdcacd99cccac4405356b1bf
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServicesDisabledProfile.java=63d8395a943dc32dadf0eb40c57b95e4
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServicesNonUniquePortProfile.java=4aef74cb67a2a2628e1d04ff6a4a5b31
/src/test/java/io/quarkus/redis/devservices/it/profiles/DevServicesRandomPortProfile.java=620e407a7865db692d85ddc8920d1c01
/src/test/java/io/quarkus/redis/devservices/it/utils/SocketKit.java=1c408021a5d14d57bdf709af6e364cfa
/src/test/java/io/quarkus/test/devservices/redis/BundledResource.java=af0c90479cf54b98cbb925e638687f5a
