/src/main/java/io/quarkus/signals/it/cmd/Cmd.java=da176c249818297e42d1f02fcf831ab2
/src/main/java/io/quarkus/signals/it/cmd/CmdReceivers.java=91fcfa07a1c2942cd2da414ad93506ef
/src/main/java/io/quarkus/signals/it/cmd/SignalsApp.java=d69cff2dcf9d712d5446bdf12dce123a
/src/test/java/io/quarkus/signals/it/cmd/SignalsCommandModeIT.java=6c9d0c78c31b2d7de3033374c621d88a
/src/test/java/io/quarkus/signals/it/cmd/SignalsCommandModeTest.java=588f2c216ef038335dd729c94ac98d7e
