/src/main/java/io/quarkus/narayana/jta/TransactionBeanWithEvents.java=44066b95ea2137c3b0b883db05e8d57c
/src/main/java/io/quarkus/narayana/jta/TransactionScopedBean.java=82df8028e3a7f6e98001ef1355b3696b
/src/main/java/io/quarkus/narayana/jta/TransactionalResource.java=df1304642e222bac8a94461d54826c77
/src/test/java/io/quarkus/narayana/jta/BaseTransactionTest.java=fa2c93aeabe703524ecfeadbc204948a
/src/test/java/io/quarkus/narayana/jta/JdbcObjectStoreTestProfile.java=5105e05f32ba0c3565a56db9d35772c3
/src/test/java/io/quarkus/narayana/jta/TransactionConfPropTest.java=547f1049c95c96394b36bd509309a451
/src/test/java/io/quarkus/narayana/jta/TransactionJdbcObjectStoreIT.java=b9af7a2ccb0b9dcf1a903314798f9cce
/src/test/java/io/quarkus/narayana/jta/TransactionJdbcObjectStoreTest.java=9e3ef42d1e96c572488e93ce81eeb9b5
/src/test/java/io/quarkus/narayana/jta/TransactionScopeQuarkusTransactionBeginCommitTest.java=1d639a01b733b7f59561dc4d60f27cf4
/src/test/java/io/quarkus/narayana/jta/TransactionScopeQuarkusTransactionRunnerTest.java=feb2cc82493e5dc590788cc25d5f10ed
/src/test/java/io/quarkus/narayana/jta/TransactionScopeTransactionalTest.java=19b14670ff08d845d234b62d5e9e3bbd
/src/test/java/io/quarkus/narayana/jta/TransactionScopeUserTransactionTest.java=1ceb6c8c1fdee8ee27280673b706c319
/src/test/java/io/quarkus/narayana/jta/TransactionalITCase.java=537cd5fb3276cc9c6187ac238b6cd69c
/src/test/java/io/quarkus/narayana/jta/TransactionalTestCase.java=e92496490753e0ab080c8a8006afc5f8
